// ─── CARRERAS DISPUTADAS ─────────────────────────────────────────────────────
window.races = [
    { round: 1, name: 'Australia',  short: 'AUS', flag: '🇦🇺', winner: 'George Russell' },
    { round: 2, name: 'China',      short: 'CHN', flag: '🇨🇳', winner: 'Kimi Antonelli',  sprint: true },
    { round: 3, name: 'Japón',      short: 'JPN', flag: '🇯🇵', winner: 'Kimi Antonelli' },
    { round: 4, name: 'Bahrein',    short: 'BHR', flag: '🇧🇭', winner: '—' },
    { round: 5, name: 'Arabia S.',  short: 'KSA', flag: '🇸🇦', winner: '—' },
    { round: 6, name: 'Miami',      short: 'MIA', flag: '🇺🇸', winner: 'Lando Norris',    sprint: true },
    { round: 7, name: 'Canadá',     short: 'CAN', flag: '🇨🇦', winner: 'Kimi Antonelli',  sprint: true },
];

// ─── COLORES HEX POR EQUIPO ──────────────────────────────────────────────────
window.teamColors = {
    'mercedes':        '#00D2BE',
    'ferrari':         '#E10600',
    'mclaren':         '#FF8700',
    'red-bull-racing': '#3671C6',
    'alpine':          '#0093CC',
    'racing-bulls':    '#6692FF',
    'haas':            '#B6BABD',
    'williams':        '#64C4FF',
    'audi':            '#C0C0C0',
    'cadillac':        '#00827F',
    'aston-martin':    '#358C75',
};

// ─── PILOTOS ─────────────────────────────────────────────────────────────────
window.drivers = [
    {
        slug: 'kimi-antonelli',
        position: 1,
        name: 'Kimi Antonelli',
        flag: '🇮🇹', flagImg: 'img/flags/it.png',
        photo: 'img/drivers/kimi-antonelli.jpg',
        team: 'Mercedes', teamSlug: 'mercedes',
        points: 131, code: 'ANT', colorClass: 'team-mercedes',
        nationality: 'Italiano', age: 19,
        wins: 3, podiums: 5, poles: 2, fastestLaps: 1,
        bio: 'Joven fenómeno de Mercedes que lidera el campeonato con velocidad y madurez sorprendente para sus 19 años.',
        raceResults: [2, 1, 1, null, null, 3, 1],
    },
    {
        slug: 'george-russell',
        position: 2,
        name: 'George Russell',
        flag: '🇬🇧', flagImg: 'img/flags/gb.png',
        photo: 'img/drivers/george-russell.jpg',
        team: 'Mercedes', teamSlug: 'mercedes',
        points: 88, code: 'RUS', colorClass: 'team-mercedes',
        nationality: 'Británico', age: 27,
        wins: 1, podiums: 4, poles: 3, fastestLaps: 2,
        bio: 'Russell mantiene el ritmo de Mercedes con actuaciones consistentes y rápidas en clasificación.',
        raceResults: [1, 2, 4, null, null, 2, 2],
    },
    {
        slug: 'charles-leclerc',
        position: 3,
        name: 'Charles Leclerc',
        flag: '🇲🇨', flagImg: 'img/flags/mc.png',
        photo: 'img/drivers/charles-leclerc.jpg',
        team: 'Ferrari', teamSlug: 'ferrari',
        points: 75, code: 'LEC', colorClass: 'team-ferrari',
        nationality: 'Monegasco', age: 27,
        wins: 1, podiums: 3, poles: 1, fastestLaps: 1,
        bio: 'Leclerc sigue siendo la punta de lanza de Ferrari con velocidad pura y determinación.',
        raceResults: [3, 4, 2, null, null, 5, 4],
    },
    {
        slug: 'lewis-hamilton',
        position: 4,
        name: 'Lewis Hamilton',
        flag: '🇬🇧', flagImg: 'img/flags/gb.png',
        photo: 'img/drivers/lewis-hamilton.jpg',
        team: 'Ferrari', teamSlug: 'ferrari',
        points: 72, code: 'HAM', colorClass: 'team-ferrari',
        nationality: 'Británico', age: 40,
        wins: 0, podiums: 3, poles: 0, fastestLaps: 0,
        bio: 'Hamilton aporta experiencia y eficacia a Ferrari en una lucha cerrada por el título.',
        raceResults: [4, 3, 3, null, null, 4, 3],
    },
    {
        slug: 'lando-norris',
        position: 5,
        name: 'Lando Norris',
        flag: '🇬🇧', flagImg: 'img/flags/gb.png',
        photo: 'img/drivers/lando-norris.jpg',
        team: 'McLaren', teamSlug: 'mclaren',
        points: 58, code: 'NOR', colorClass: 'team-mclaren',
        nationality: 'Británico', age: 25,
        wins: 1, podiums: 2, poles: 0, fastestLaps: 1,
        bio: 'Norris combina agresividad y buen manejo para mantener a McLaren en la pelea.',
        raceResults: [5, 6, 6, null, null, 1, 6],
    },
    {
        slug: 'oscar-piastri',
        position: 6,
        name: 'Oscar Piastri',
        flag: '🇦🇺', flagImg: 'img/flags/au.png',
        photo: 'img/drivers/oscar-piastri.jpg',
        team: 'McLaren', teamSlug: 'mclaren',
        points: 48, code: 'PIA', colorClass: 'team-mclaren',
        nationality: 'Australiano', age: 24,
        wins: 0, podiums: 1, poles: 0, fastestLaps: 0,
        bio: 'Piastri muestra consistencia y velocidad, consolidando el buen momento de McLaren.',
        raceResults: [6, 5, 5, null, null, 6, 5],
    },
    {
        slug: 'max-verstappen',
        position: 7,
        name: 'Max Verstappen',
        flag: '🇳🇱', flagImg: 'img/flags/nl.png',
        photo: 'img/drivers/max-verstappen.jpg',
        team: 'Red Bull Racing', teamSlug: 'red-bull-racing',
        points: 43, code: 'VER', colorClass: 'team-redbull',
        nationality: 'Holandés', age: 27,
        wins: 0, podiums: 1, poles: 0, fastestLaps: 1,
        bio: 'El tricampeón sigue sumando puntos pero Red Bull lucha con el nuevo reglamento técnico.',
        raceResults: [7, 7, 7, null, null, 7, 7],
    },
    {
        slug: 'pierre-gasly',
        position: 8,
        name: 'Pierre Gasly',
        flag: '🇫🇷', flagImg: 'img/flags/fr.png',
        photo: 'img/drivers/pierre-gasly.jpg',
        team: 'Alpine', teamSlug: 'alpine',
        points: 20, code: 'GAS', colorClass: 'team-alpine',
        nationality: 'Francés', age: 29,
        wins: 0, podiums: 0, poles: 0, fastestLaps: 0,
        bio: 'Gasly aporta velocidad y solidez a Alpine con puntos clave en cada carrera.',
        raceResults: [8, 8, 9, null, null, 8, 14],
    },
    {
        slug: 'oliver-bearman',
        position: 9,
        name: 'Oliver Bearman',
        flag: '🇬🇧', flagImg: 'img/flags/gb.png',
        photo: 'img/drivers/oliver-bearman.jpg',
        team: 'Haas', teamSlug: 'haas',
        points: 18, code: 'BEA', colorClass: 'team-haas',
        nationality: 'Británico', age: 20,
        wins: 0, podiums: 0, poles: 0, fastestLaps: 0,
        bio: 'Joven talento en Haas que ya sumó puntos importantes y demostró gran adaptabilidad.',
        raceResults: [9, 9, 8, null, null, 9, 9],
    },
    {
        slug: 'liam-lawson',
        position: 10,
        name: 'Liam Lawson',
        flag: '🇳🇿', flagImg: 'img/flags/nz.png',
        photo: 'img/drivers/liam-lawson.jpg',
        team: 'Racing Bulls', teamSlug: 'racing-bulls',
        points: 16, code: 'LAW', colorClass: 'team-racing-bulls',
        nationality: 'Neozelandés', age: 23,
        wins: 0, podiums: 0, poles: 0, fastestLaps: 0,
        bio: 'Lawson aporta ritmo y consistencia al equipo Racing Bulls en su primera temporada completa.',
        raceResults: [10, 10, 10, null, null, 10, 10],
    },
    {
        slug: 'franco-colapinto',
        position: 11,
        name: 'Franco Colapinto',
        flag: '🇦🇷', flagImg: 'img/flags/ar.png',
        photo: 'img/drivers/franco-colapinto.jpg',
        team: 'Alpine', teamSlug: 'alpine',
        points: 15, code: 'COL', colorClass: 'team-alpine',
        nationality: 'Argentino', age: 21,
        wins: 0, podiums: 0, poles: 0, fastestLaps: 0,
        bio: 'El piloto de San Andrés de Giles sorprende con madurez y velocidad en su primera temporada completa en F1.',
        raceResults: [14, 10, 16, null, null, 7, null],
    },
    {
        slug: 'isack-hadjar',
        position: 12,
        name: 'Isack Hadjar',
        flag: '🇫🇷', flagImg: 'img/flags/fr.png',
        photo: 'img/drivers/isack-hadjar.jpg',
        team: 'Red Bull Racing', teamSlug: 'red-bull-racing',
        points: 14, code: 'HAD', colorClass: 'team-redbull',
        nationality: 'Francés', age: 19,
        wins: 0, podiums: 0, poles: 0, fastestLaps: 0,
        bio: 'Promesa de Red Bull que ya suma puntos importantes y acelera carrera a carrera.',
        raceResults: [11, 11, 11, null, null, 11, 11],
    },
    {
        slug: 'carlos-sainz',
        position: 13,
        name: 'Carlos Sainz',
        flag: '🇪🇸', flagImg: 'img/flags/es.png',
        photo: 'img/drivers/carlos-sainz.jpg',
        team: 'Williams', teamSlug: 'williams',
        points: 6, code: 'SAI', colorClass: 'team-williams',
        nationality: 'Español', age: 30,
        wins: 0, podiums: 0, poles: 0, fastestLaps: 0,
        bio: 'Sainz suma puntos importantes y da experiencia clave al proyecto de Williams.',
        raceResults: [12, 12, 12, null, null, 12, 13],
    },
    {
        slug: 'arvid-lindblad',
        position: 14,
        name: 'Arvid Lindblad',
        flag: '🇸🇪', flagImg: 'img/flags/se.png',
        photo: 'img/drivers/arvid-lindblad.jpg',
        team: 'Racing Bulls', teamSlug: 'racing-bulls',
        points: 5, code: 'LIN', colorClass: 'team-racing-bulls',
        nationality: 'Sueco', age: 18,
        wins: 0, podiums: 0, poles: 0, fastestLaps: 0,
        bio: 'Lindblad aporta consistencia a Racing Bulls con un buen ritmo de carrera en su debut en F1.',
        raceResults: [13, 13, 13, null, null, 13, 12],
    },
    {
        slug: 'gabriel-bortoleto',
        position: 15,
        name: 'Gabriel Bortoleto',
        flag: '🇧🇷', flagImg: 'img/flags/br.png',
        photo: 'img/drivers/gabriel-bortoleto.jpg',
        team: 'Audi', teamSlug: 'audi',
        points: 2, code: 'BOR', colorClass: 'team-audi',
        nationality: 'Brasileño', age: 20,
        wins: 0, podiums: 0, poles: 0, fastestLaps: 0,
        bio: 'Rookie de Audi que ya logró sus primeros puntos en la temporada inaugural del equipo alemán.',
        raceResults: [16, 14, 14, null, null, 14, 15],
    },
    {
        slug: 'esteban-ocon',
        position: 16,
        name: 'Esteban Ocon',
        flag: '🇫🇷', flagImg: 'img/flags/fr.png',
        photo: 'img/drivers/esteban-ocon.jpg',
        team: 'Haas', teamSlug: 'haas',
        points: 1, code: 'OCO', colorClass: 'team-haas',
        nationality: 'Francés', age: 28,
        wins: 0, podiums: 0, poles: 0, fastestLaps: 0,
        bio: 'Ocon aporta experiencia y puntos valiosos para Haas en esta nueva etapa de su carrera.',
        raceResults: [15, 15, 15, null, null, 15, 16],
    },
    {
        slug: 'alexander-albon',
        position: 17,
        name: 'Alexander Albon',
        flag: '🇹🇭', flagImg: 'img/flags/th.png',
        photo: 'img/drivers/alexander-albon.jpg',
        team: 'Williams', teamSlug: 'williams',
        points: 1, code: 'ALB', colorClass: 'team-williams',
        nationality: 'Tailandés', age: 29,
        wins: 0, podiums: 0, poles: 0, fastestLaps: 0,
        bio: 'Albon ayuda a Williams con actuaciones sólidas y un estilo de manejo agresivo.',
        raceResults: [17, 16, 17, null, null, 16, 8],
    },
    {
        slug: 'nico-hulkenberg',
        position: 18,
        name: 'Nico Hülkenberg',
        flag: '🇩🇪', flagImg: 'img/flags/de.png',
        photo: 'img/drivers/nico-hulkenberg.jpg',
        team: 'Audi', teamSlug: 'audi',
        points: 0, code: 'HUL', colorClass: 'team-audi',
        nationality: 'Alemán', age: 37,
        wins: 0, podiums: 0, poles: 0, fastestLaps: 0,
        bio: 'Hülkenberg aporta experiencia y estabilidad al ambicioso proyecto de Audi en Fórmula 1.',
        raceResults: [18, 17, 18, null, null, 17, 17],
    },
    {
        slug: 'valtteri-bottas',
        position: 19,
        name: 'Valtteri Bottas',
        flag: '🇫🇮', flagImg: 'img/flags/fi.png',
        photo: 'img/drivers/valtteri-bottas.jpg',
        team: 'Cadillac', teamSlug: 'cadillac',
        points: 0, code: 'BOT', colorClass: 'team-cadillac',
        nationality: 'Finlandés', age: 35,
        wins: 0, podiums: 0, poles: 0, fastestLaps: 0,
        bio: 'Bottas aporta veteranía y técnica de set-up a Cadillac en el inicio de su proyecto en F1.',
        raceResults: [19, 18, 19, null, null, 18, 18],
    },
    {
        slug: 'sergio-perez',
        position: 20,
        name: 'Sergio Pérez',
        flag: '🇲🇽', flagImg: 'img/flags/mx.png',
        photo: 'img/drivers/sergio-perez.jpg',
        team: 'Cadillac', teamSlug: 'cadillac',
        points: 0, code: 'PER', colorClass: 'team-cadillac',
        nationality: 'Mexicano', age: 35,
        wins: 0, podiums: 0, poles: 0, fastestLaps: 0,
        bio: 'Pérez aporta experiencia y liderazgo a Cadillac en su primera temporada en la parrilla.',
        raceResults: [20, 19, 20, null, null, 19, 19],
    },
    {
        slug: 'lance-stroll',
        position: 21,
        name: 'Lance Stroll',
        flag: '🇨🇦', flagImg: 'img/flags/ca.png',
        photo: 'img/drivers/lance-stroll.jpg',
        team: 'Aston Martin', teamSlug: 'aston-martin',
        points: 0, code: 'STR', colorClass: 'team-aston',
        nationality: 'Canadiense', age: 26,
        wins: 0, podiums: 0, poles: 0, fastestLaps: 0,
        bio: 'Stroll sigue trabajando para encontrar el ritmo en el Aston Martin de nueva generación.',
        raceResults: [21, 20, 21, null, null, 20, 20],
    },
    {
        slug: 'fernando-alonso',
        position: 22,
        name: 'Fernando Alonso',
        flag: '🇪🇸', flagImg: 'img/flags/es.png',
        photo: 'img/drivers/fernando-alonso.jpg',
        team: 'Aston Martin', teamSlug: 'aston-martin',
        points: 0, code: 'ALO', colorClass: 'team-aston',
        nationality: 'Español', age: 44,
        wins: 0, podiums: 0, poles: 0, fastestLaps: 0,
        bio: 'Alonso aporta experiencia y sabiduría incomparables a Aston Martin en esta temporada de reinicio.',
        raceResults: [22, 21, 22, null, null, 21, 21],
    }
];

// ─── ESCUDERÍAS ──────────────────────────────────────────────────────────────
window.constructors = [
    {
        slug: 'mercedes', position: 1, name: 'Mercedes',
        flag: '🇩🇪', flagImg: 'img/flags/de.png',
        originFlag: 'img/flags/de.png', baseFlag: 'img/flags/gb.png',
        points: 219, code: 'MER', colorClass: 'team-mercedes', color: '#00D2BE',
        image: 'img/mercedes.png',
        base: 'Brackley, Reino Unido', origin: 'Alemania',
        teamPrincipal: 'Toto Wolff', engine: 'Mercedes', championships: 8,
        topDrivers: ['Kimi Antonelli', 'George Russell'],
        description: 'Mercedes lidera el campeonato con velocidad extrema. Antonelli y Russell forman una de las mejores duplas del paddock.',
    },
    {
        slug: 'ferrari', position: 2, name: 'Ferrari',
        flag: '🇮🇹', flagImg: 'img/flags/it.png',
        originFlag: 'img/flags/it.png', baseFlag: 'img/flags/it.png',
        points: 147, code: 'FER', colorClass: 'team-ferrari', color: '#E10600',
        image: 'img/ferrari.png',
        base: 'Maranello, Italia', origin: 'Italia',
        teamPrincipal: 'Frédéric Vasseur', engine: 'Ferrari', championships: 16,
        topDrivers: ['Charles Leclerc', 'Lewis Hamilton'],
        description: 'Ferrari se mantiene fuerte con dos pilotos de altísimo nivel. Leclerc y Hamilton buscan el título juntos.',
    },
    {
        slug: 'mclaren', position: 3, name: 'McLaren',
        flag: '🇬🇧', flagImg: 'img/flags/gb.png',
        originFlag: 'img/flags/gb.png', baseFlag: 'img/flags/gb.png',
        points: 106, code: 'MCL', colorClass: 'team-mclaren', color: '#FF8700',
        image: 'img/mclaren.png',
        base: 'Woking, Reino Unido', origin: 'Reino Unido',
        teamPrincipal: 'Andrea Stella', engine: 'Mercedes', championships: 8,
        topDrivers: ['Lando Norris', 'Oscar Piastri'],
        description: 'McLaren ofrece velocidad y momentos brillantes con una pareja joven y muy competitiva.',
    },
    {
        slug: 'red-bull-racing', position: 4, name: 'Red Bull Racing',
        flag: '🇦🇹', flagImg: 'img/flags/at.png',
        originFlag: 'img/flags/at.png', baseFlag: 'img/flags/gb.png',
        points: 57, code: 'RBR', colorClass: 'team-redbull', color: '#3671C6',
        image: 'img/red-bull.png',
        base: 'Milton Keynes, Reino Unido', origin: 'Austria',
        teamPrincipal: 'Christian Horner', engine: 'Red Bull Powertrains', championships: 7,
        topDrivers: ['Max Verstappen', 'Isack Hadjar'],
        description: 'Red Bull Racing sigue sumando con una mezcla de experiencia y juventud, aunque el nuevo reglamento los alejó del liderato.',
    },
    {
        slug: 'alpine', position: 5, name: 'Alpine',
        flag: '🇫🇷', flagImg: 'img/flags/fr.png',
        originFlag: 'img/flags/fr.png', baseFlag: 'img/flags/gb.png',
        points: 35, code: 'ALP', colorClass: 'team-alpine', color: '#0093CC',
        image: 'img/alpine.png',
        base: 'Enstone, Reino Unido', origin: 'Francia',
        teamPrincipal: 'Otmar Szafnauer', engine: 'Renault', championships: 1,
        topDrivers: ['Pierre Gasly', 'Franco Colapinto'],
        description: 'Alpine suma puntos con buen rendimiento técnico. Colapinto es la gran revelación argentina del equipo.',
    },
    {
        slug: 'racing-bulls', position: 6, name: 'Racing Bulls',
        flag: '🇮🇹', flagImg: 'img/flags/it.png',
        originFlag: 'img/flags/at.png', baseFlag: 'img/flags/it.png',
        points: 21, code: 'RBL', colorClass: 'team-racing-bulls', color: '#6692FF',
        image: 'img/visa-rb.png',
        base: 'Faenza, Italia', origin: 'Austria / Italia',
        teamPrincipal: 'Laurent Mekies', engine: 'Red Bull Powertrains', championships: 0,
        topDrivers: ['Liam Lawson', 'Arvid Lindblad'],
        description: 'Racing Bulls progresa con una de las duplas más jóvenes de la parrilla. Lawson y Lindblad buscan puntos cada fin de semana.',
    },
    {
        slug: 'haas', position: 7, name: 'Haas',
        flag: '🇺🇸', flagImg: 'img/flags/us.png',
        originFlag: 'img/flags/us.png', baseFlag: 'img/flags/us.png',
        points: 19, code: 'HAA', colorClass: 'team-haas', color: '#B6BABD',
        image: 'img/haas.png',
        base: 'Kannapolis, EE.UU.', origin: 'Estados Unidos',
        teamPrincipal: 'Ayao Komatsu', engine: 'Ferrari', championships: 0,
        topDrivers: ['Oliver Bearman', 'Esteban Ocon'],
        description: 'Haas combina juventud y experiencia. Bearman sorprende como uno de los rookies más sólidos de la temporada.',
    },
    {
        slug: 'williams', position: 8, name: 'Williams',
        flag: '🇬🇧', flagImg: 'img/flags/gb.png',
        originFlag: 'img/flags/gb.png', baseFlag: 'img/flags/gb.png',
        points: 7, code: 'WIL', colorClass: 'team-williams', color: '#64C4FF',
        image: 'img/williams.png',
        base: 'Grove, Reino Unido', origin: 'Reino Unido',
        teamPrincipal: 'James Vowles', engine: 'Mercedes', championships: 9,
        topDrivers: ['Carlos Sainz', 'Alexander Albon'],
        description: 'Williams suma puntos gracias a dos pilotos experimentados. Sainz aporta liderazgo técnico para acelerar el desarrollo.',
    },
    {
        slug: 'audi', position: 9, name: 'Audi',
        flag: '🇩🇪', flagImg: 'img/flags/de.png',
        originFlag: 'img/flags/de.png', baseFlag: 'img/flags/de.png',
        points: 2, code: 'AUD', colorClass: 'team-audi', color: '#C0C0C0',
        image: 'img/audi.png',
        base: 'Hinwil, Suiza', origin: 'Alemania',
        teamPrincipal: 'Mattia Binotto', engine: 'Audi', championships: 0,
        topDrivers: ['Gabriel Bortoleto', 'Nico Hülkenberg'],
        description: 'Audi debuta en F1 con ambición y ya suma sus primeros puntos. Bortoleto es la joven promesa del equipo.',
    },
    {
        slug: 'cadillac', position: 10, name: 'Cadillac',
        flag: '🇺🇸', flagImg: 'img/flags/us.png',
        originFlag: 'img/flags/us.png', baseFlag: 'img/flags/us.png',
        points: 0, code: 'CAD', colorClass: 'team-cadillac', color: '#00827F',
        image: 'img/cadillac.png',
        base: 'Detroit, EE.UU.', origin: 'Estados Unidos',
        teamPrincipal: 'Mario Andretti Jr.', engine: 'Ferrari', championships: 0,
        topDrivers: ['Valtteri Bottas', 'Sergio Pérez'],
        description: 'Cadillac inicia su aventura en F1 con dos pilotos muy experimentados. El equipo trabaja para encontrar el ritmo del pelotón.',
    },
    {
        slug: 'aston-martin', position: 11, name: 'Aston Martin',
        flag: '🇬🇧', flagImg: 'img/flags/gb.png',
        originFlag: 'img/flags/gb.png', baseFlag: 'img/flags/gb.png',
        points: 0, code: 'AST', colorClass: 'team-aston', color: '#358C75',
        image: 'img/aston-martin.png',
        base: 'Silverstone, Reino Unido', origin: 'Reino Unido',
        teamPrincipal: 'Andy Cowell', engine: 'Mercedes', championships: 0,
        topDrivers: ['Lance Stroll', 'Fernando Alonso'],
        description: 'Aston Martin busca su primer punto mientras ajusta el paquete técnico. Alonso aporta su experiencia única al desarrollo.',
    }
];

// ─── CALENDARIO ───────────────────────────────────────────────────────────────
window.calendar = [
    { round:1,  date:'2026-03-08', name:'GP de Australia',     circuit:'Melbourne',        flag:'🇦🇺', time:null,    sprint:false, status:'done',     winner:'George Russell' },
    { round:2,  date:'2026-03-15', name:'GP de China',         circuit:'Shanghai',         flag:'🇨🇳', time:null,    sprint:true,  status:'done',     winner:'Kimi Antonelli' },
    { round:3,  date:'2026-03-29', name:'GP de Japón',         circuit:'Suzuka',           flag:'🇯🇵', time:null,    sprint:false, status:'done',     winner:'Kimi Antonelli' },
    { round:4,  date:'2026-04-12', name:'GP de Bahrein',       circuit:'Sakhir',           flag:'🇧🇭', time:null,    sprint:false, status:'done',     winner:'—' },
    { round:5,  date:'2026-04-19', name:'GP de Arabia Saudita',circuit:'Jeddah',           flag:'🇸🇦', time:null,    sprint:false, status:'done',     winner:'—' },
    { round:6,  date:'2026-05-03', name:'GP de Miami',         circuit:'Miami Gardens',    flag:'🇺🇸', time:'14:00', sprint:true,  status:'done',     winner:'Lando Norris' },
    { round:7,  date:'2026-05-24', name:'GP de Canadá',        circuit:'Montreal',         flag:'🇨🇦', time:'17:00', sprint:true,  status:'done',     winner:'Kimi Antonelli' },
    { round:8,  date:'2026-06-08', name:'GP de Mónaco',        circuit:'Montecarlo',       flag:'🇲🇨', time:'10:00', sprint:false, status:'next',     winner:null },
    { round:9,  date:'2026-06-14', name:'GP de Barcelona',     circuit:'Catalunya',        flag:'🇪🇸', time:'10:00', sprint:false, status:'upcoming', winner:null },
    { round:10, date:'2026-06-28', name:'GP de Austria',       circuit:'Spielberg',        flag:'🇦🇹', time:'10:00', sprint:false, status:'upcoming', winner:null },
    { round:11, date:'2026-07-05', name:'GP de Gran Bretaña',  circuit:'Silverstone',      flag:'🇬🇧', time:'11:00', sprint:true,  status:'upcoming', winner:null },
    { round:12, date:'2026-07-19', name:'GP de Bélgica',       circuit:'Spa-Francorchamps',flag:'🇧🇪', time:'10:00', sprint:false, status:'upcoming', winner:null },
    { round:13, date:'2026-07-26', name:'GP de Hungría',       circuit:'Budapest',         flag:'🇭🇺', time:'10:00', sprint:false, status:'upcoming', winner:null },
    { round:14, date:'2026-08-23', name:'GP de Países Bajos',  circuit:'Zandvoort',        flag:'🇳🇱', time:'10:00', sprint:true,  status:'upcoming', winner:null },
    { round:15, date:'2026-09-06', name:'GP de Italia',        circuit:'Monza',            flag:'🇮🇹', time:'10:00', sprint:false, status:'upcoming', winner:null },
    { round:16, date:'2026-09-13', name:'GP de España',        circuit:'Madrid',           flag:'🇪🇸', time:'10:00', sprint:false, status:'upcoming', winner:null },
    { round:17, date:'2026-09-27', name:'GP de Azerbaiyán',    circuit:'Bakú',             flag:'🇦🇿', time:'08:00', sprint:false, status:'upcoming', winner:null },
    { round:18, date:'2026-10-11', name:'GP de Singapur',      circuit:'Marina Bay',       flag:'🇸🇬', time:'09:00', sprint:true,  status:'upcoming', winner:null },
    { round:19, date:'2026-10-25', name:'GP de EE.UU.',        circuit:'Austin',           flag:'🇺🇸', time:'17:00', sprint:false, status:'upcoming', winner:null },
    { round:20, date:'2026-11-01', name:'GP de México',        circuit:'CDMX',             flag:'🇲🇽', time:'17:00', sprint:false, status:'upcoming', winner:null },
    { round:21, date:'2026-11-08', name:'GP de Brasil',        circuit:'Interlagos',       flag:'🇧🇷', time:'14:00', sprint:false, status:'upcoming', winner:null },
    { round:22, date:'2026-11-22', name:'GP de Las Vegas',     circuit:'Las Vegas Strip',  flag:'🇺🇸', time:'01:00', sprint:false, status:'upcoming', winner:null, lateNight:true },
    { round:23, date:'2026-11-29', name:'GP de Qatar',         circuit:'Lusail',           flag:'🇶🇦', time:'13:00', sprint:false, status:'upcoming', winner:null },
    { round:24, date:'2026-12-06', name:'GP de Abu Dhabi',     circuit:'Yas Marina',       flag:'🇦🇪', time:'10:00', sprint:false, status:'upcoming', winner:null },
];

// ─── UTILIDADES ───────────────────────────────────────────────────────────────
window.slugify = function(text) {
    return String(text).toLowerCase().normalize('NFD')
        .replace(/\p{Diacritic}/gu, '').replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
};
window.findDriverBySlug  = s => window.drivers.find(d => d.slug === s);
window.findConstructorBySlug = s => window.constructors.find(t => t.slug === s);
window.getTeamColor = s => window.teamColors[s] || '#888';
window.getCumulativePoints = function(driver) {
    const pts = [25,18,15,12,10,8,6,4,2,1];
    let cum = 0;
    return (driver.raceResults || []).map(pos => {
        if (pos !== null && pos >= 1 && pos <= 10) cum += pts[pos-1];
        return cum;
    });
};
