window.drivers = [
    {
        slug: 'kimi-antonelli',
        position: 1,
        name: 'Kimi Antonelli',
        team: 'Mercedes',
        teamSlug: 'mercedes',
        points: 131,
        code: 'ME',
        colorClass: 'team-mercedes',
        nationality: 'Italiano',
        age: 19,
        wins: 3,
        podiums: 7,
        bio: 'Joven fenómeno de Mercedes que lidera la tabla con velocidad y madurez sorprendente.'
    },
    {
        slug: 'george-russell',
        position: 2,
        name: 'George Russell',
        team: 'Mercedes',
        teamSlug: 'mercedes',
        points: 88,
        code: 'ME',
        colorClass: 'team-mercedes',
        nationality: 'Británico',
        age: 26,
        wins: 2,
        podiums: 5,
        bio: 'Russell mantiene el ritmo de Mercedes con actuaciones consistentes y rápidas en calificación.'
    },
    {
        slug: 'charles-leclerc',
        position: 3,
        name: 'Charles Leclerc',
        team: 'Ferrari',
        teamSlug: 'ferrari',
        points: 75,
        code: 'FE',
        colorClass: 'team-ferrari',
        nationality: 'Monegasco',
        age: 26,
        wins: 1,
        podiums: 4,
        bio: 'Leclerc sigue siendo la punta de lanza de Ferrari con velocidad pura y determinación.'
    },
    {
        slug: 'lewis-hamilton',
        position: 4,
        name: 'Lewis Hamilton',
        team: 'Ferrari',
        teamSlug: 'ferrari',
        points: 72,
        code: 'FE',
        colorClass: 'team-ferrari',
        nationality: 'Británico',
        age: 38,
        wins: 2,
        podiums: 4,
        bio: 'Hamilton aporta experiencia y eficacia a Ferrari en una lucha cerrada por el título.'
    },
    {
        slug: 'lando-norris',
        position: 5,
        name: 'Lando Norris',
        team: 'McLaren',
        teamSlug: 'mclaren',
        points: 58,
        code: 'MC',
        colorClass: 'team-mclaren',
        nationality: 'Británico',
        age: 25,
        wins: 1,
        podiums: 3,
        bio: 'Norris combina agresividad y buen manejo para mantener a McLaren en la pelea.'
    },
    {
        slug: 'oscar-piastri',
        position: 6,
        name: 'Oscar Piastri',
        team: 'McLaren',
        teamSlug: 'mclaren',
        points: 48,
        code: 'MC',
        colorClass: 'team-mclaren',
        nationality: 'Australiano',
        age: 23,
        wins: 0,
        podiums: 2,
        bio: 'Piastri muestra consistencia y velocidad, consolidando el buen momento de McLaren.'
    },
    {
        slug: 'max-verstappen',
        position: 7,
        name: 'Max Verstappen',
        team: 'Red Bull Racing',
        teamSlug: 'red-bull-racing',
        points: 43,
        code: 'RB',
        colorClass: 'team-redbull',
        nationality: 'Holandés',
        age: 26,
        wins: 1,
        podiums: 3,
        bio: 'El campeón sigue sumando puntos importantes y mantiene a Red Bull Racing competitivo.'
    },
    {
        slug: 'pierre-gasly',
        position: 8,
        name: 'Pierre Gasly',
        team: 'Alpine',
        teamSlug: 'alpine',
        points: 20,
        code: 'AL',
        colorClass: 'team-alpine',
        nationality: 'Francés',
        age: 28,
        wins: 0,
        podiums: 1,
        bio: 'Gasly aporta velocidad y solidez a Alpine con puntos claves en cada carrera.'
    },
    {
        slug: 'oliver-bearman',
        position: 9,
        name: 'Oliver Bearman',
        team: 'Haas',
        teamSlug: 'haas',
        points: 18,
        code: 'HA',
        colorClass: 'team-haas',
        nationality: 'Británico',
        age: 19,
        wins: 0,
        podiums: 0,
        bio: 'Joven talento en Haas que ya sumó puntos y demostró gran adaptabilidad.'
    },
    {
        slug: 'liam-lawson',
        position: 10,
        name: 'Liam Lawson',
        team: 'Racing Bulls',
        teamSlug: 'racing-bulls',
        points: 16,
        code: 'RB',
        colorClass: 'team-racing-bulls',
        nationality: 'Neozelandés',
        age: 23,
        wins: 0,
        podiums: 0,
        bio: 'Lawson aporta ritmo y consistencia al equipo Racing Bulls.'
    },
    {
        slug: 'franco-colapinto',
        position: 11,
        name: 'Franco Colapinto',
        team: 'Alpine',
        teamSlug: 'alpine',
        points: 15,
        code: 'AL',
        colorClass: 'team-alpine',
        nationality: 'Argentino',
        age: 21,
        wins: 0,
        podiums: 0,
        bio: 'Colapinto aporta juventud y frescura a la alineación de Alpine.'
    },
    {
        slug: 'isack-hadjar',
        position: 12,
        name: 'Isack Hadjar',
        team: 'Red Bull Racing',
        teamSlug: 'red-bull-racing',
        points: 14,
        code: 'RB',
        colorClass: 'team-redbull',
        nationality: 'Francés',
        age: 18,
        wins: 0,
        podiums: 0,
        bio: 'Promesa de Red Bull que ya suma puntos y acelera en cada carrera.'
    },
    {
        slug: 'carlos-sainz',
        position: 13,
        name: 'Carlos Sainz',
        team: 'Williams',
        teamSlug: 'williams',
        points: 6,
        code: 'WI',
        colorClass: 'team-williams',
        nationality: 'Español',
        age: 29,
        wins: 0,
        podiums: 0,
        bio: 'Sainz suma puntos importantes y da experiencia al regreso de Williams.'
    },
    {
        slug: 'arvid-lindblad',
        position: 14,
        name: 'Arvid Lindblad',
        team: 'Racing Bulls',
        teamSlug: 'racing-bulls',
        points: 5,
        code: 'RB',
        colorClass: 'team-racing-bulls',
        nationality: 'Sueco',
        age: 24,
        wins: 0,
        podiums: 0,
        bio: 'Lindblad aporta consistencia a Racing Bulls con buen ritmo de carrera.'
    },
    {
        slug: 'gabriel-bortoleto',
        position: 15,
        name: 'Gabriel Bortoleto',
        team: 'Audi',
        teamSlug: 'audi',
        points: 2,
        code: 'AU',
        colorClass: 'team-audi',
        nationality: 'Brasileño',
        age: 19,
        wins: 0,
        podiums: 0,
        bio: 'Rookie de Audi que ya logró sus primeros puntos en la temporada.'
    },
    {
        slug: 'esteban-ocon',
        position: 16,
        name: 'Esteban Ocon',
        team: 'Haas',
        teamSlug: 'haas',
        points: 1,
        code: 'HA',
        colorClass: 'team-haas',
        nationality: 'Francés',
        age: 28,
        wins: 0,
        podiums: 0,
        bio: 'Ocon aporta experiencia y puntos valiosos para Haas.'
    },
    {
        slug: 'alexander-albon',
        position: 17,
        name: 'Alexander Albon',
        team: 'Williams',
        teamSlug: 'williams',
        points: 1,
        code: 'WI',
        colorClass: 'team-williams',
        nationality: 'Tailandés',
        age: 28,
        wins: 0,
        podiums: 0,
        bio: 'Albon ayuda a Williams con actuaciones sólidas y un estilo agresivo.'
    },
    {
        slug: 'nico-hulkenberg',
        position: 18,
        name: 'Nico Hülkenberg',
        team: 'Audi',
        teamSlug: 'audi',
        points: 0,
        code: 'AU',
        colorClass: 'team-audi',
        nationality: 'Alemán',
        age: 36,
        wins: 0,
        podiums: 0,
        bio: 'Hülkenberg aporta experiencia y estabilidad al proyecto reciente de Audi.'
    },
    {
        slug: 'valtteri-bottas',
        position: 19,
        name: 'Valtteri Bottas',
        team: 'Cadillac',
        teamSlug: 'cadillac',
        points: 0,
        code: 'CD',
        colorClass: 'team-cadillac',
        nationality: 'Finlandés',
        age: 35,
        wins: 0,
        podiums: 0,
        bio: 'Bottas aporta veteranía y técnica a Cadillac en el inicio de su proyecto.'
    },
    {
        slug: 'sergio-perez',
        position: 20,
        name: 'Sergio Pérez',
        team: 'Cadillac',
        teamSlug: 'cadillac',
        points: 0,
        code: 'CD',
        colorClass: 'team-cadillac',
        nationality: 'Mexicano',
        age: 34,
        wins: 0,
        podiums: 0,
        bio: 'Pérez aporta experiencia y liderazgo a Cadillac, aunque todavía no ha sumado puntos.'
    },
    {
        slug: 'lance-stroll',
        position: 21,
        name: 'Lance Stroll',
        team: 'Aston Martin',
        teamSlug: 'aston-martin',
        points: 0,
        code: 'AM',
        colorClass: 'team-aston',
        nationality: 'Canadiense',
        age: 25,
        wins: 0,
        podiums: 0,
        bio: 'Stroll sigue trabajando para encontrar velocidad en el Aston Martin.'
    },
    {
        slug: 'fernando-alonso',
        position: 22,
        name: 'Fernando Alonso',
        team: 'Aston Martin',
        teamSlug: 'aston-martin',
        points: 0,
        code: 'AM',
        colorClass: 'team-aston',
        nationality: 'Español',
        age: 44,
        wins: 0,
        podiums: 0,
        bio: 'Alonso aporta experiencia y sabiduría a Aston Martin en esta temporada de reinicio.'
    }
];

window.constructors = [
    {
        slug: 'mercedes',
        position: 1,
        name: 'Mercedes',
        points: 219,
        code: 'ME',
        colorClass: 'team-mercedes',
        image: 'img/mercedes.png',
        base: 'Brackley, Reino Unido',
        teamPrincipal: 'Toto Wolff',
        engine: 'Mercedes',
        championships: 8,
        topDrivers: ['Kimi Antonelli', 'George Russell'],
        description: 'Mercedes lidera la tabla con velocidad extrema y un equipo muy sólido.'
    },
    {
        slug: 'ferrari',
        position: 2,
        name: 'Ferrari',
        points: 147,
        code: 'FE',
        colorClass: 'team-ferrari',
        image: 'img/ferrari.png',
        base: 'Maranello, Italia',
        teamPrincipal: 'Frédéric Vasseur',
        engine: 'Ferrari',
        championships: 16,
        topDrivers: ['Charles Leclerc', 'Lewis Hamilton'],
        description: 'Ferrari se mantiene fuerte con dos pilotos de alto nivel y un ritmo constante.'
    },
    {
        slug: 'mclaren',
        position: 3,
        name: 'McLaren',
        points: 106,
        code: 'MC',
        colorClass: 'team-mclaren',
        image: 'img/mclaren.png',
        base: 'Woking, Reino Unido',
        teamPrincipal: 'Andrea Stella',
        engine: 'Mercedes',
        championships: 8,
        topDrivers: ['Lando Norris', 'Oscar Piastri'],
        description: 'McLaren ofrece velocidad y momentos brillantes con una pareja joven y competitiva.'
    },
    {
        slug: 'red-bull-racing',
        position: 4,
        name: 'Red Bull Racing',
        points: 57,
        code: 'RB',
        colorClass: 'team-redbull',
        image: 'img/red-bull.png',
        base: 'Milton Keynes, Reino Unido',
        teamPrincipal: 'Christian Horner',
        engine: 'Red Bull Powertrains',
        championships: 7,
        topDrivers: ['Max Verstappen', 'Isack Hadjar'],
        description: 'Red Bull Racing sigue sumando con una mezcla de experiencia y juventud.'
    },
    {
        slug: 'alpine',
        position: 5,
        name: 'Alpine',
        points: 35,
        code: 'AL',
        colorClass: 'team-alpine',
        image: 'img/alpine.png',
        base: 'Enstone, Reino Unido',
        teamPrincipal: 'Otmar Szafnauer',
        engine: 'Renault',
        championships: 1,
        topDrivers: ['Pierre Gasly', 'Franco Colapinto'],
        description: 'Alpine suma puntos con buen rendimiento técnico y pilotos sólidos.'
    },
    {
        slug: 'racing-bulls',
        position: 6,
        name: 'Racing Bulls',
        points: 21,
        code: 'RB',
        colorClass: 'team-racing-bulls',
        image: 'img/visa-rb.png',
        base: 'Bologna, Italia',
        teamPrincipal: 'Franz Tost',
        engine: 'Honda',
        championships: 0,
        topDrivers: ['Liam Lawson', 'Arvid Lindblad'],
        description: 'Racing Bulls se estrena con buenos resultados y progreso constante.'
    },
    {
        slug: 'haas',
        position: 7,
        name: 'Haas',
        points: 19,
        code: 'HA',
        colorClass: 'team-haas',
        image: 'img/haas.png',
        base: 'Kannapolis, EE. UU.',
        teamPrincipal: 'Guenther Steiner',
        engine: 'Ferrari',
        championships: 0,
        topDrivers: ['Oliver Bearman', 'Esteban Ocon'],
        description: 'Haas se impone con llamados por jóvenes talentos y experiencia de carrera.'
    },
    {
        slug: 'williams',
        position: 8,
        name: 'Williams',
        points: 7,
        code: 'WI',
        colorClass: 'team-williams',
        image: 'img/williams.png',
        base: 'Grove, Reino Unido',
        teamPrincipal: 'James Vowles',
        engine: 'Mercedes',
        championships: 9,
        topDrivers: ['Carlos Sainz', 'Alexander Albon'],
        description: 'Williams suma puntos gracias a dos pilotos veteranos y un auto competitivo.'
    },
    {
        slug: 'audi',
        position: 9,
        name: 'Audi',
        points: 2,
        code: 'AU',
        colorClass: 'team-audi',
        image: 'img/audi.png',
        base: 'Ingolstadt, Alemania',
        teamPrincipal: 'Ola Källenius',
        engine: 'Audi',
        championships: 0,
        topDrivers: ['Gabriel Bortoleto', 'Nico Hülkenberg'],
        description: 'Audi entra con fuerza al campeonato y ya suma puntos con sus pilotos jóvenes.'
    },
    {
        slug: 'cadillac',
        position: 10,
        name: 'Cadillac',
        points: 0,
        code: 'CD',
        colorClass: 'team-cadillac',
        image: 'img/cadillac.png',
        base: 'Detroit, EE. UU.',
        teamPrincipal: 'Mary Barra',
        engine: 'Cadillac EV',
        championships: 0,
        topDrivers: ['Valtteri Bottas', 'Sergio Pérez'],
        description: 'Cadillac inicia su temporada con equipo nuevo y pilotos experimentados.'
    },
    {
        slug: 'aston-martin',
        position: 11,
        name: 'Aston Martin',
        points: 0,
        code: 'AM',
        colorClass: 'team-aston',
        image: 'img/aston-martin.png',
        base: 'Silverstone, Reino Unido',
        teamPrincipal: 'Mike Krack',
        engine: 'Mercedes',
        championships: 0,
        topDrivers: ['Lance Stroll', 'Fernando Alonso'],
        description: 'Aston Martin busca su primer punto mientras ajusta su paquete técnico.'
    }
];

window.slugify = function (text) {
    return String(text)
        .toLowerCase()
        .normalize('NFD')
        .replace(/\p{Diacritic}/gu, '')
        .replace(/[^a-z0-9]+/g, '-')
        .replace(/(^-|-$)/g, '');
};

window.findDriverBySlug = function (slug) {
    return drivers.find(driver => driver.slug === slug);
};

window.findConstructorBySlug = function (slug) {
    return constructors.find(team => team.slug === slug);
};
